@echo off

if exist tasks/session.txt (del /f tasks\session.txt
goto boot) else (exit)

:boot
set startdir=%~dp0

set content=
for /f "delims=" %%i in ('type config\gitlocation.txt') do set content=%%i

set v=
for /f "delims=" %%i in ('type tasks\version.txt') do set v=%%i

title SpigotMC Updater v.%v%

echo MSGBOX "Make sure to always backup your files incase an update breaks" >> %temp%\TEMPmessage.vbs
call %temp%\TEMPmessage.vbs
del %temp%\TEMPmessage.vbs /f /q

if exist %content% (goto start) else (goto error1)

:start
cls
@echo Welcome to SpigotMC Updater v.%v%
echo.
@echo What task do you want to run? Must use numbers and press enter.
@echo 1. Update Buildtools
@echo 2. Run Buildtools
@echo 3. Clean Buildtools Folder
@echo 4. Repair a plugin with Spigot's Special Recipe
@echo 5. Grab BungeeCord (Only needed if you are hosting a network.)
@echo 6. Read Changelogs (For nerds)
@echo 7. Update SpigotMC Updater
@echo 8. Close this script safely
:commanderror
Set /P "_1=>" || Set _1=NothingChosen
If "%_1%"=="NothingChosen" goto :commandnotfound
If /i "%_1%"=="1" goto update
If /i "%_1%"=="2" goto run
If /i "%_1%"=="3" goto clean
If /i "%_1%"=="4" goto plugin
If /i "%_1%"=="5" goto bungee
If /i "%_1%"=="6" goto changelog
If /i "%_1%"=="7" goto updatetool
If /i "%_1%"=="8" goto exit

:commandnotfound
@echo Command not found. Try help for help menu
goto commanderror

:update
cls
start /b /wait %startdir%tasks\delbt.bat
%content% --login -i -c "sleep 3s"
%content% --login -i -c "curl -o tasks/Buildtools_Files/BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastBuild/artifact/target/BuildTools.jar"
if exist %startdir%tasks\Buildtools_Files\BuildTools.jar (@echo Updated BuildTools) else (@echo An error has occured. Make sure folder has read, write, and execute access.)
goto start

:run
cls
@echo Warning: exiting while this is running may cause something to break, and not move buildtools files at the right time leaving a mess until you run this command again.

if exist tasks\Buildtools_Files\BuildTools.jar (@echo Running BuildTools.jar) else (@echo Buildtools.jar is missing
echo.
@echo Grabbing BuildTools.jar from hub.spigotmc.org
echo.
%content% --login -i -c "curl -o tasks/Buildtools_Files/BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastBuild/artifact/target/BuildTools.jar"
echo.
@echo Grabbed, and will attempt to run BuildTools.jar
)
@echo I am a dummy file xD >> tasks\session.txt
cls
start /b /wait config\version.txt
set version=
for /f "delims=" %%i in ('type config\version.txt') do set version=%%i

start /b /wait %startdir%tasks\Buildtools_Files\run.bat

cd %startdir%

cls

set datetime=
for /f %%a in ('powershell -Command "Get-Date -format yyyy_MM_dd__HH_mm_ss"') do set datetime=%%a

if exist BuildTools.log.txt (rename BuildTools.log.txt Buildtools.log.%datetime%.txt
move BuildTools.log.*.txt %startdir%logs)

@echo Moving Server jars into folder %startdir%serverjars\
%content% --login -i -c "sleep 1s"
echo.
@echo Moving Spigot
%content% --login -i -c "sleep 3s"
echo.
if exist %startdir%tasks/Buildtools_Files/spigot-*.jar (move %startdir%tasks\Buildtools_Files\spigot-*.jar %startdir%serverjars
%content% --login -i -c "sleep 3s"
echo.
if exist %startdir%tasks/Buildtools_Files/spigot-*.jar (@echo Failed to move Spigot) else (@echo Moved Spigot service Successfully)
) else (@echo File doesnt exist)
echo.
%content% --login -i -c "sleep 2s"
@echo Moving Craftbukkit
%content% --login -i -c "sleep 1s"
echo.
if exist %startdir%tasks/Buildtools_Files/craftbukkit-*.jar (move %startdir%tasks\Buildtools_Files\craftbukkit-*.jar %startdir%serverjars
echo.
%content% --login -i -c "sleep 2s"
if exist %startdir%tasks/Buildtools_Files/craftbukkit-*.jar (@echo Failed to move Craftbukkit) else (@echo Moved Craftbukkit service Successfully)
) else (@echo File doesnt exist)
@echo.
@echo Copying Spigot API's to api folder
%content% --login -i -c "sleep 1s"
echo.
copy %startdir%tasks\Buildtools_Files\Spigot\Spigot-API\target\spigot-api-*.jar %startdir%api
cls
@echo Finished running BuildTools
%content% --login -i -c "sleep 3s"
goto start

:clean
cls
@echo Are you sure you want to clear all of Buildtools Files
Set /P "_clear=(Y, N)" || Set _clear=NothingChosen
If "%_clear%"=="NothingChosen" goto start
If /i "%_clear%"=="Y" goto cleanrun
If /i "%_clear%"=="y" goto cleanrun
If /i "%_clear%"=="N" goto start
If /i "%_clear%"=="n" goto start
:cleanrun
@echo Deleting every folder in %startdir%Buildtools_Files\ that was generated by BuildTools.jar
cd .
rmdir /q /s %startdir%tasks\Buildtools_Files\apache-maven-3.2.5 %startdir%tasks\Buildtools_Files\BuildData %startdir%tasks\Buildtools_Files\Bukkit %startdir%tasks\Buildtools_Files\CraftBukkit %startdir%tasks\Buildtools_Files\Spigot %startdir%tasks\Buildtools_Files\work
if exist %startdir%tasks\Buildtools_Files\apache-maven-3.2.5 (@echo Cleaning of %startdir%Buildtools_Files\apache-maven-3.2.5 Failed. Make sure the folder has read, write, and execute enabled.
goto start) else (@echo Cleaning of %startdir%Buildtools_Files\apache-maven-3.2.5 was Successful)
%content% --login -i -c "sleep 1s"
if exist %startdir%tasks\Buildtools_Files\BuildData (@echo Cleaning of %startdir%Buildtools_Files\BuildData Failed. Make sure the folder has read, write, and execute enabled.
goto start) else (@echo Cleaning of %startdir%Buildtools_Files\BuildData was Successful)
%content% --login -i -c "sleep 1s"
if exist %startdir%tasks\Buildtools_Files\Bukkit (@echo Cleaning of %startdir%Buildtools_Files\Bukkit Failed. Make sure the folder has read, write, and execute enabled.
goto start) else (@echo Cleaning of %startdir%Buildtools_Files\Bukkit was Successful)
%content% --login -i -c "sleep 1s"
if exist %startdir%tasks\Buildtools_Files\CraftBukkit (@echo Cleaning of %startdir%Buildtools_Files\CraftBukkit Failed. Make sure the folder has read, write, and execute enabled.
goto start) else (@echo Cleaning of %startdir%Buildtools_Files\CraftBukkit was Successful)
%content% --login -i -c "sleep 1s"
if exist %startdir%tasks\Buildtools_Files\CraftBukkit (@echo Cleaning of %startdir%Buildtools_Files\CraftBukkit Failed. Make sure the folder has read, write, and execute enabled.
goto start) else (@echo Cleaning of %startdir%Buildtools_Files\CraftBukkit was Successful)
%content% --login -i -c "sleep 1s"
if exist %startdir%tasks\Buildtools_Files\work (@echo Cleaning of %startdir%Buildtools_Files\work Failed. Make sure the folder has read, write, and execute enabled.
goto start) else (@echo Cleaning of %startdir%Buildtools_Files\work was Successful)
%content% --login -i -c "sleep 1s"
echo.
@echo All Buildtools Files were removed.
%content% --login -i -c "sleep 3s"
goto start

:plugin
@echo I am a dummy file xD >> tasks\session.txt
cls
start /b /wait task\plugin_repair_tool.bat
@echo Finished using Plugin Repair Tool by SpigotMC Updater. Thanks to md_5 for making the original repair script as he does not endorse or maintains this script.
%content% --login -i -c "sleep 3s"
goto start

:bungee
cls
@echo Updating BungeeCord and its modules.
If not exist %startdir%bungee (md bungee)
If not exist %startdir%bungee\modules (md bungee\modules)

If exist bungee\BungeeCord.jar (del /f bungee\BungeeCord.jar)
%content% --login -i -c "sleep 1s"
If exist bungee\modules\cmd_find.jar (del /f bungee\modules\cmd_find.jar)
%content% --login -i -c "sleep 1s"
If exist bungee\modules\cmd_server.jar (del /f bungee\modules\cmd_server.jar)
%content% --login -i -c "sleep 1s"
If exist bungee\modules\cmd_send.jar (del /f bungee\modules\cmd_send.jar)
%content% --login -i -c "sleep 1s"
If exist bungee\modules\cmd_list.jar (del /f bungee\modules\cmd_list.jar)
%content% --login -i -c "sleep 1s"
If exist bungee\modules\cmd_alert.jar (del /f bungee\modules\cmd_alert.jar)
%content% --login -i -c "sleep 1s"
If exist bungee\modules\reconnect_yaml.jar (del /f bungee\modules\reconnect_yaml.jar)
%content% --login -i -c "sleep 1s"
@echo Downloading BungeeCord.jar
%content% --login -i -c "sleep 5s"
%content% --login -i -c "curl -o bungee/BungeeCord.jar http://ci.md-5.net/job/BungeeCord/lastBuild/artifact/bootstrap/target/BungeeCord.jar"
%content% --login -i -c "sleep 1s"
@echo Downloading modules/cmd_alert.jar
%content% --login -i -c "curl -o bungee/modules/cmd_alert.jar http://ci.md-5.net/job/BungeeCord/lastBuild/artifact/module/cmd-alert/target/cmd_alert.jar"
%content% --login -i -c "sleep 1s"
@echo Downloading modules/cmd_find.jar
%content% --login -i -c "curl -o bungee/modules/cmd_find.jar http://ci.md-5.net/job/BungeeCord/lastBuild/artifact/module/cmd-alert/target/cmd_find.jar"
%content% --login -i -c "sleep 1s"
@echo Downloading modules/cmd_list.jar
%content% --login -i -c "curl -o bungee/modules/cmd_list.jar http://ci.md-5.net/job/BungeeCord/lastBuild/artifact/module/cmd-alert/target/cmd_list.jar"
%content% --login -i -c "sleep 1s"
@echo Downloading modules/cmd_server.jar
%content% --login -i -c "curl -o bungee/modules/cmd_server.jar http://ci.md-5.net/job/BungeeCord/lastBuild/artifact/module/cmd-alert/target/cmd_server.jar"
%content% --login -i -c "sleep 1s"
@echo Downloading modules/cmd_send.jar
%content% --login -i -c "curl -o bungee/modules/cmd_send.jar http://ci.md-5.net/job/BungeeCord/lastBuild/artifact/module/cmd-alert/target/cmd_send.jar"
%content% --login -i -c "sleep 1s"
@echo Downloading modules/reconnect_yaml.jar
%content% --login -i -c "curl -o bungee/modules/reconnect_yaml.jar http://ci.md-5.net/job/BungeeCord/lastBuild/artifact/module/cmd-alert/target/reconnect_yaml.jar"
@echo Updated BungeeCord and all its Modules

:rerun
start "bungeelocation Config Option" /wait config\bungeelocation.txt

set bungee=
for /f "delims=" %%i in ('type config\bungeelocation.txt') do set bungee=%%i

if exist %bungee% (goto bungeecopy) else (goto rerun)

:bungeecopy
cls
@echo Replacing old update(s) with new ones ;)

if exist %bungee%BungeeCord.jar (del /f %bungee%BungeeCord.jar
%content% --login -i -c "sleep 1s"
del /f %bungee%modules\cmd_find.jar
%content% --login -i -c "sleep 1s"
del /f %bungee%modules\cmd_server.jar
%content% --login -i -c "sleep 1s"
del /f %bungee%modules\cmd_send.jar
%content% --login -i -c "sleep 1s"
del /f %bungee%modules\cmd_list.jar
%content% --login -i -c "sleep 1s"
del /f %bungee%modules\cmd_alert.jar
%content% --login -i -c "sleep 1s"
del /f %bungee%modules\reconnect_yaml.jar
@echo Deleted old Updates) else (@echo Nothing to delete at all. This can be ignored)


%content% --login -i -c "sleep 1s"
cls

@echo Placing in new Updated jars into folder %bungee%
%content% --login -i -c "sleep 1s"

copy bungee\Bungeecord.jar %bungee% /v /-y
%content% --login -i -c "sleep 1s"
copy bungee\modules\cmd_find.jar %bungee%modules /v /-y
%content% --login -i -c "sleep 1s"
copy bungee\modules\cmd_server.jar %bungee%modules /v /-y
%content% --login -i -c "sleep 1s"
copy bungee\modules\cmd_send.jar %bungee%modules /v /-y
%content% --login -i -c "sleep 1s"
copy bungee\modules\cmd_list.jar %bungee%modules /v /-y
%content% --login -i -c "sleep 1s"
copy bungee\modules\cmd_alert.jar %bungee%modules /v /-y
%content% --login -i -c "sleep 1s"
copy bungee\modules\reconnect_yaml.jar %bungee%modules /v /-y

goto start

:changelog
cls

start /b /wait tasks\changelog.bat

pause

goto start

:error1

start "SpigotMC Updater Reloaded | gitlocation.txt" /wait config\gitlocation.txt

set content=
for /f "delims=" %%i in ('type config\gitlocation.txt') do set content=%%i

if exist %content% (goto start) else (@echo Failed 2nd attempt. Launching your browser.)

explorer "https://github.com/git-for-windows/git/releases/download/v2.7.2.windows.1/Git-2.7.2-64-bit.exe"

:exit
cls
@echo Thanks for using SpigotMC Updater v.%v% by Legoman99573. Updated by ShadowCable.
@pause
exit
