@echo off

if exist tasks/Buildtools_Files/cleanup.bat (
	@echo [Info] Loading Cleanup Module... >> log.txt
) else (
	exit
)

set startdir=%~dp0

set v=
for /f "delims=" %%i in ('type tasks\version.txt') do set v=%%i

title Running SpigotMC Updater v.%v% Cleanup Module

cd %startdir%

set content=..\..\Git\bin\bash.exe

@echo Deleting every folder in %startdir% that was generated by BuildTools.jar
cd .
rmdir /q /s apache-maven-3.2.5 BuildData Bukkit CraftBukkit Spigot work
%content% --login -i -c "sleep 60s"

if exist apache-maven-3.2.5/ (
	powershell.exe -command write-host "Cleaning of %startdir%apache-maven-3.2.5 Failed. Make sure %startdir% has Read/Write enabled." -f red
    @echo [ERROR] Cleaning of %startdir%apache-maven-3.2.5 Failed. Make sure %startdir% has Read/Write enabled. >> ..\..\log.txt
) else (
    powershell.exe -command write-host "Cleaning of %startdir%apache-maven-3.2.5 was Successful" -f green
	@echo [Info] Cleaning of %startdir%apache-maven-3.2.5 was Successful >> log.txt
)
%content% --login -i -c "sleep 5s"

if exist BuildData/ (
    powershell.exe -command write-host "Cleaning of %startdir%BuildData Failed. Make sure %startdir% has Read/Write enabled." -f red
	@echo [ERROR] Cleaning of %startdir%BuildData Failed. Make sure %startdir% has Read/Write enabled. >> ..\..\log.txt
) else (
	powershell.exe -command write-host "Cleaning of %startdir%BuildData was Successful" -f green
    @echo [Info] Cleaning of %startdir%BuildData was Successful ..\..\log.txt
)
%content% --login -i -c "sleep 5s"

if exist Bukkit/ (
	powershell.exe -command write-host " Cleaning of %startdir%Buildtools_Files\Bukkit Failed. Make sure %startdir% has Read/Write enabled." -f red
	@echo [ERROR] Cleaning of %startdir%Buildtools_Files\Bukkit Failed. Make sure %startdir% has Read/Write enabled. >> ..\..\log.txt
) else (
	powershell.exe -command write-host "Cleaning of %startdir%Buildtools_Files\Bukkit was Successful" -f green
	@echo [Info] Cleaning of %startdir%Buildtools_Files\Bukkit was Successful >> ..\..\log.txt
)
%content% --login -i -c "sleep 5s"

if exist CraftBukkit/ (
	powershell.exe -command write-host "Cleaning of %startdir%CraftBukkit Failed. Make sure %startdir% has Read/Write enabled." -f red
	@echo [ERROR] Cleaning of %startdir%CraftBukkit Failed. Make sure %startdir% has Read/Write enabled. >> ..\..\log.txt
) else (
	powershell.exe -command write-host "Cleaning of %startdir%CraftBukkit was Successful" -f green
	@echo [Info] Cleaning of %startdir%CraftBukkit was Successful >> ..\..\log.txt
)
%content% --login -i -c "sleep 5s"

if exist CraftBukkit/ (
	powershell.exe -command write-host "Cleaning of %startdir%CraftBukkit Failed. Make sure %startdir% has Read/Write enabled." -f red
	@echo [ERROR] Cleaning of %startdir%CraftBukkit Failed. Make sure %startdir% has Read/Write enabled. >> ..\..\log.txt
) else (
	powershell.exe -command write-host "Cleaning of %startdir%CraftBukkit was Successful" -f green
	@echo [Info] Cleaning of %startdir%CraftBukkit was Successful >> ..\..\log.txt
)
%content% --login -i -c "sleep 5s"

if exist work/ (
	powershell.exe -command write-host "Cleaning of %startdir%work Failed. Make sure %startdir% has Read/Write enabled." -f red
	@echo [ERROR] Cleaning of %startdir%work Failed. Make sure %startdir% has Read/Write enabled. >> ..\..\log.txt
) else (
	powershell.exe -command write-host "Cleaning of %startdir%Buildtools_Files\work was Successful" -f green
	@echo [Info] Cleaning of %startdir%Buildtools_Files\work was Successful >> ..\..\log.txt
)
%content% --login -i -c "sleep 20s"

cd ..\..\
exit
